# x prints the integer 3 in the first example and an error in the second example.  In the first example x is 
# created with an outer scope and changed inside the block, but it can still be referenced since it was created
# outside of the scope of the block.  In the second example, x is created inside the block and can't be 
# referenced inside of the block.